version: "3.7"
services:
  app:
    build:
      args:
        user: biswajit
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: larvel-app
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - bjnetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: glue
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_USER: biswajit
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - bjnetwork

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: larvel-nginx 
    container_name: webserver 
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - db
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bjnetwork

networks:
  bjnetwork:
    driver: bridge

volumes:
  dbdata:
    driver: local

